### ISSUE TITLE
Support extra arguments for `sbatch` in the submit command

### ISSUE THREAD

**Issue by mcleish7** [eugene-prout/slutil#47]
**Description:**
Adding ability to pass command line options to slurm e.g. sbatch --dependency=afterok:624713 test_4.sh

**Solution should:**
Have the ability to execute 'sbatch --dependency=afterok:624713 test_4.sh' or other command line options for slurm with slutil.

**Comment by eugene-prout** [comment]
This will be done in 2 stages.
1. Make slutil not break on extra arguments to `slutil submit`
2. Make slutil aware of certain arguments to `sbatch` and extra data from e.g. make a report showing all the dependencies of a job
